// Export reviewed drawings as a Word-compatible HTML report
export function exportReport(drawings, title = 'Drawing QA Report') {
  const reviewed = drawings.filter(d => d.result)
  if (!reviewed.length) return
  const rl = { RED:'🔴 RED', AMBER:'🟡 AMBER', GREEN:'🟢 GREEN', NA:'⚪ N/A' }
  const rc = { RED:'#C00000', AMBER:'#C55A11', GREEN:'#375623', NA:'#666' }
  const rb = { RED:'#FCE4E4', AMBER:'#FEF2CC', GREEN:'#EBF1DE', NA:'#F2F2F2' }
  const phaseRows = phases => phases.map(p => {
    const findings = p.naReason
      ? `<tr><td colspan="3" style="font-style:italic;color:#888;padding:4pt 8pt;">N/A: ${p.naReason}</td></tr>`
      : p.findings?.length
        ? p.findings.map(f=>`<tr><td style="width:80pt;padding:4pt 8pt;border:0.5pt solid #ccc;background:${rb[f.rag]||'#fff'};color:${rc[f.rag]||'#333'};font-weight:bold;font-size:9pt;">${rl[f.rag]||f.rag}</td><td style="padding:4pt 8pt;border:0.5pt solid #ccc;font-size:9pt;">${f.finding}</td><td style="padding:4pt 8pt;border:0.5pt solid #ccc;font-size:9pt;">${f.action}</td></tr>`).join('')
        : `<tr><td colspan="3" style="padding:4pt 8pt;color:#375623;font-size:9pt;">✓ No issues.</td></tr>`
    return `<tr style="background:#40404c;"><td colspan="2" style="padding:5pt 8pt;color:#e3ded2;font-weight:bold;font-size:10pt;border:none;">Phase ${p.id} — ${p.name}</td><td style="padding:5pt 8pt;background:${rb[p.rag]||'#f7f5f1'};color:${rc[p.rag]||'#333'};font-weight:bold;font-size:10pt;border:none;text-align:right;">${rl[p.rag]||p.rag}</td></tr>${findings}`
  }).join('')
  const sections = reviewed.map(d => {
    const r = d.result
    const critRows = r.criticalFindings?.length
      ? r.criticalFindings.map((f,i)=>`<tr><td style="width:24pt;padding:4pt 8pt;border:0.5pt solid #f5c1c1;background:#FCE4E4;color:#C00000;font-weight:bold;font-size:9pt;">${i+1}</td><td style="padding:4pt 8pt;border:0.5pt solid #f5c1c1;font-size:9pt;">${f.phase}</td><td style="padding:4pt 8pt;border:0.5pt solid #f5c1c1;color:#C00000;font-weight:bold;font-size:9pt;">${f.finding}</td><td style="padding:4pt 8pt;border:0.5pt solid #f5c1c1;font-size:9pt;">${f.action}</td></tr>`).join('')
      : `<tr><td colspan="4" style="padding:4pt 8pt;color:#375623;font-size:9pt;">No critical findings.</td></tr>`
    return `<div style="page-break-inside:avoid;"><table style="width:100%;border-collapse:collapse;margin-bottom:4pt;"><tr><td style="background:#de134d;padding:8pt 12pt;border:none;"><span style="font-size:14pt;font-weight:bold;color:#fff;font-family:Arial;">${r.drawingRef}</span><br><span style="font-size:10pt;color:rgba(255,255,255,0.85);font-family:Arial;">${r.drawingType}</span></td><td style="background:${rb[r.overallRAG]||'#f7f5f1'};padding:8pt 12pt;text-align:right;border:none;width:120pt;"><span style="font-size:12pt;font-weight:bold;color:${rc[r.overallRAG]||'#333'};font-family:Arial;">${rl[r.overallRAG]||r.overallRAG}</span></td></tr></table><table style="width:100%;border-collapse:collapse;margin-bottom:8pt;"><tr><td style="background:#f7f5f1;padding:8pt 12pt;border-left:3pt solid #de134d;font-size:10pt;font-family:Arial;color:#40404c;"><strong>Issue Recommendation:</strong> ${r.issueRecommendation}</td></tr><tr><td style="padding:6pt 12pt;font-size:10pt;font-family:Arial;color:#555;border-top:0.5pt solid #e0ddd7;">${r.summary}</td></tr></table><p style="font-size:10pt;font-weight:bold;color:#40404c;font-family:Arial;margin:8pt 0 4pt;">Critical Findings</p><table style="width:100%;border-collapse:collapse;margin-bottom:12pt;"><tr style="background:#40404c;"><th style="padding:5pt 8pt;color:#e3ded2;font-size:9pt;text-align:left;border:none;">#</th><th style="padding:5pt 8pt;color:#e3ded2;font-size:9pt;text-align:left;border:none;">Phase</th><th style="padding:5pt 8pt;color:#e3ded2;font-size:9pt;text-align:left;border:none;">Finding</th><th style="padding:5pt 8pt;color:#e3ded2;font-size:9pt;text-align:left;border:none;">Action</th></tr>${critRows}</table><p style="font-size:10pt;font-weight:bold;color:#40404c;font-family:Arial;margin:8pt 0 4pt;">QA Phase Results</p><table style="width:100%;border-collapse:collapse;margin-bottom:20pt;"><tr style="background:#40404c;"><th colspan="2" style="padding:5pt 8pt;color:#e3ded2;font-size:9pt;text-align:left;border:none;">Phase</th><th style="padding:5pt 8pt;color:#e3ded2;font-size:9pt;text-align:left;border:none;">Status</th></tr>${phaseRows(r.phases||[])}</table></div>`
  }).join('<br style="page-break-after:always;">')
  const batchRows = reviewed.map(d=>{const r=d.result;return`<tr><td style="padding:5pt 8pt;border:0.5pt solid #ccc;font-weight:bold;font-size:9pt;">${r.drawingRef}</td><td style="padding:5pt 8pt;border:0.5pt solid #ccc;font-size:9pt;">${r.drawingType}</td><td style="padding:5pt 8pt;border:0.5pt solid #ccc;font-weight:bold;color:${rc[r.overallRAG]||'#333'};background:${rb[r.overallRAG]||'#fff'};font-size:9pt;">${rl[r.overallRAG]||r.overallRAG}</td><td style="padding:5pt 8pt;border:0.5pt solid #ccc;font-size:9pt;">${r.criticalFindings?.length||0}</td><td style="padding:5pt 8pt;border:0.5pt solid #ccc;font-size:9pt;">${r.issueRecommendation}</td></tr>`}).join('')
  const redC=reviewed.filter(d=>d.result?.overallRAG==='RED').length
  const ambC=reviewed.filter(d=>d.result?.overallRAG==='AMBER').length
  const grnC=reviewed.filter(d=>d.result?.overallRAG==='GREEN').length
  const html=`<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns="http://www.w3.org/TR/REC-html40"><head><meta charset="utf-8"><style>@page{size:A4;margin:1.5cm 2cm;}body{font-family:Arial,sans-serif;font-size:10pt;color:#40404c;margin:0;}h1{font-size:20pt;color:#de134d;margin:0 0 4pt;}h2{font-size:13pt;color:#40404c;border-bottom:1pt solid #de134d;padding-bottom:3pt;margin:16pt 0 6pt;}p{margin:4pt 0;}table{border-collapse:collapse;}th{font-weight:bold;}</style></head><body><table style="width:100%;border-collapse:collapse;margin-bottom:16pt;border-bottom:2pt solid #de134d;"><tr><td style="padding:0 0 8pt;border:none;"><h1>Reds10 Group</h1><p style="font-size:13pt;color:#40404c;margin:0;font-weight:bold;">${title}</p></td><td style="text-align:right;vertical-align:bottom;padding:0 0 8pt;border:none;"><p style="font-size:9pt;color:#888;margin:0;">Date: ${new Date().toLocaleDateString('en-GB',{day:'2-digit',month:'long',year:'numeric'})}</p><p style="font-size:9pt;color:#888;margin:0;">Drawings reviewed: ${reviewed.length}</p><p style="font-size:9pt;color:#888;margin:0;"><span style="color:#C00000;font-weight:bold;">${redC} RED</span> &nbsp;<span style="color:#C55A11;font-weight:bold;">${ambC} AMBER</span> &nbsp;<span style="color:#375623;font-weight:bold;">${grnC} GREEN</span></p></td></tr></table><h2>Batch Summary</h2><table style="width:100%;border-collapse:collapse;margin-bottom:20pt;"><tr style="background:#40404c;"><th style="padding:5pt 8pt;color:#e3ded2;font-size:9pt;text-align:left;border:none;">Drawing Ref</th><th style="padding:5pt 8pt;color:#e3ded2;font-size:9pt;text-align:left;border:none;">Type</th><th style="padding:5pt 8pt;color:#e3ded2;font-size:9pt;text-align:left;border:none;">Overall RAG</th><th style="padding:5pt 8pt;color:#e3ded2;font-size:9pt;text-align:left;border:none;">Critical</th><th style="padding:5pt 8pt;color:#e3ded2;font-size:9pt;text-align:left;border:none;">Verdict</th></tr>${batchRows}</table><h2>Detailed Drawing Reports</h2>${sections}<table style="width:100%;border-collapse:collapse;margin-top:20pt;border-top:1pt solid #e0ddd7;"><tr><td style="padding:8pt 0;font-size:8pt;color:#999;border:none;">Generated by Reds10 Drawing QA | Reds10 Group | ${new Date().toLocaleDateString('en-GB')}</td><td style="text-align:right;padding:8pt 0;font-size:8pt;color:#de134d;font-weight:bold;border:none;">CONFIDENTIAL</td></tr></table></body></html>`
  const blob = new Blob(['\ufeff',html],{type:'application/msword'})
  const a = document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=`Reds10-QA-${new Date().toISOString().slice(0,10)}.doc`; a.click()
}
